package alibailian

// https://help.aliyun.com/zh/model-studio/getting-started/models

var ModelList = []string{
	"qwen-3.7-max",
	"qwen-3.7-plus",
	"qwen-3.6-plus",
	"qwen-3.6-flash",
	"qwen-3.5-plus",
	"qwen3-max",
	"qwen3-max-preview",
	"qwen3-plus",
	"qwen3-flash",
	"qwen3-coder-plus",
	"qwen3-235b-a22b",
	"qwen3-32b",
	"qwen3-30b-a3b",
	"qwen3.5-35b-a3b",
	"qwen3.6-35b-a3b",
	"qwen-max",
	"qwen-max-latest",
	"qwen-plus",
	"qwen-plus-latest",
	"qwen-turbo",
	"qwen-turbo-latest",
	"qwen-coder-plus",
	"qwen-coder-turbo",
	"qwen-3-coder-next",
	"qwen-long",
	"qwen-mt-plus",
	"qwen-mt-turbo",
	"qwq-32b-preview",
	"qwq-plus",
	"qwen-vl-max",
	"qwen-vl-plus",
	"qwen-vl-ocr",
	"qwen-omni-turbo",
	"text-embedding-v3",
	"text-embedding-v4",
	"deepseek-r1",
	"deepseek-v3",
	"deepseek-v3.1",
	"deepseek-v3.2",
	"deepseek-v4-flash",
	"deepseek-v4-pro",
	"kimi-k2-0711-preview",
	"kimi-k2-0905-preview",
	"kimi-k2.6",
	"kimi-k2.7",
	"kimi-k2.7-code",
}
