package siliconflow

// https://docs.siliconflow.cn/docs/getting-started

var ModelList = []string{
	"Qwen/Qwen3-235B-A22B-Instruct-2507",
	"Qwen/Qwen3-Coder-30B-A3B-Instruct",
	"Qwen/Qwen2.5-72B-Instruct",
	"Qwen/Qwen2.5-32B-Instruct",
	"Qwen/Qwen2.5-14B-Instruct",
	"Qwen/Qwen2.5-7B-Instruct",
	"Qwen/Qwen2-72B-Instruct",
	"Qwen/Qwen2-7B-Instruct",
	"Qwen/Qwen1.5-110B-Chat",
	"Qwen/Qwen1.5-32B-Chat",
	"Qwen/Qwen1.5-14B-Chat",
	"Qwen/Qwen1.5-7B-Chat",
	"deepseek-ai/DeepSeek-V3",
	"deepseek-ai/DeepSeek-V2-Chat",
	"deepseek-ai/DeepSeek-Coder-V2-Instruct",
	"deepseek-ai/deepseek-llm-67b-chat",
	"meta-llama/Meta-Llama-3-70B-Instruct",
	"meta-llama/Meta-Llama-3-8B-Instruct",
	"meta-llama/Meta-Llama-3.1-70B-Instruct",
	"meta-llama/Meta-Llama-3.1-8B-Instruct",
	"meta-llama/Meta-Llama-3.3-70B-Instruct",
	"THUDM/glm-4-9b-chat",
	"THUDM/chatglm3-6b",
	"mistralai/Mistral-7B-Instruct-v0.2",
	"mistralai/Mistral-7B-Instruct-v0.3",
	"mistralai/Mixtral-8x7B-Instruct-v0.1",
	"01-ai/Yi-1.5-9B-Chat-16K",
	"01-ai/Yi-1.5-6B-Chat",
	"01-ai/Yi-1.5-34B-Chat-16K",
	"internlm/internlm2_5-7b-chat",
	"BAAI/bge-large-en-v1.5",
	"BAAI/bge-large-zh-v1.5",
	"Pro/Qwen/Qwen2.5-7B-Instruct",
	"Pro/Qwen/Qwen2.5-14B-Instruct",
	"Pro/Qwen/Qwen2-7B-Instruct",
	"Pro/Qwen/Qwen1.5-7B-Chat",
	"Pro/deepseek-ai/DeepSeek-V3",
	"Pro/THUDM/glm-4-9b-chat",
	"Pro/THUDM/chatglm3-6b",
	"Pro/01-ai/Yi-1.5-9B-Chat-16K",
	"Pro/01-ai/Yi-1.5-6B-Chat",
	"Pro/google/gemma-2-9b-it",
	"Pro/internlm/internlm2_5-7b-chat",
	"Pro/meta-llama/Meta-Llama-3-8B-Instruct",
	"Pro/mistralai/Mistral-7B-Instruct-v0.2",
}
